name: Build with SSH Key Buildpack

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Pack CLI
      uses: buildpacks/github-actions/setup-pack@v5.0.0
    
    - name: Build with SSH Key Buildpack
      env:
        # Configure a chave SSH a partir dos secrets do GitHub
        BUILDPACK_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Configurações opcionais
        BUILDPACK_SSH_KNOWN_HOSTS: "github.com gitlab.com"
      run: |
        pack build myapp \
          --buildpack https://github.com/smartfit/buildpack-ssh-key \
          --buildpack <buildpack-da-sua-linguagem> \
          --builder paketobuildpacks/builder:base \
          --verbose
    
    - name: Test built image
      run: |
        docker run --rm myapp echo "Build successful!"

  # Job adicional para testar diferentes configurações
  test-configurations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "GitHub only"
            hosts: "github.com" 
          - name: "Multiple hosts"
            hosts: "github.com gitlab.com bitbucket.org"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Pack CLI  
      uses: buildpacks/github-actions/setup-pack@v5.0.0
    
    - name: Build with ${{ matrix.config.name }}
      env:
        BUILDPACK_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        BUILDPACK_SSH_KNOWN_HOSTS: ${{ matrix.config.hosts }}
      run: |
        pack build test-${{ matrix.config.name }} \
          --buildpack . \
          --buildpack <buildpack-da-sua-linguagem> \
          --builder paketobuildpacks/builder:base 